name: tbb
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  google_sign_in:
  firebase_auth: ^0.14.0+5
  cloud_firestore:
  rxdart:
  image_picker:
  file_picker:
  firebase_storage:
  location:
  geocoder:
  font_awesome_flutter:
  shared_preferences:
  cached_network_image: 2.0.0-rc
  image: 2.1.4
  auto_size_text: ^2.1.0
  shimmer: ^1.1.1
  swipedetector: ^1.2.0
  flutter_skeleton: ^0.1.0+1
  page_transition: "^1.1.5"
  custom_navigator: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  
  assets:
    - assets/images/

